server:
  servlet:
    context-path: /my
  port: 7777

spring:
  datasource:
    username: root
    password: ROOT
    url: jdbc:mysql://127.0.0.1:3306/mybatis_plus?ServetTimeZone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

  thymeleaf:
      encoding: UTF-8
      #开发时关闭缓存,不然没法看到实时页面
      cache: false

  mvc:
    static-path-pattern: /**
    #修改默认的静态寻址资源目录
    resources:
      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

mybatis-plus:
  typeAliasesPackage: com.cssl.pojo
  configuration:
      auto-mapping-behavior: full
      use-generated-keys: true
      map-underscore-to-camel-case: false
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl