server:
  port: 9092

spring:
  application:
    name: provider9091

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbodb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: ROOT

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  boot:
    admin:
      client:
        url: http://127.0.0.1:5052

  redis:
    host: 127.0.0.1
    port: 6379
    #password: root
    database: 0
    timeout: 10s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        max-idle: 50        # 最大空闲连接数
        min-idle: 10        # 最小空闲连接数
        max-wait:  -1s        # 等待可用连接的最大时间，负数为不限制
        max-active: -1        # 最大活跃连接数，负数为不限制




eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:6061/eureka/, http://eureka2.com:6062/eureka/
    register-with-eureka: true #向eurek server 注册
    fetch-registry: true #获取信息列表
  server:
    enable-self-preservation: false        #禁用保护,默认true
    eviction-interval-timer-in-ms: 10000    #清理间隔（默认是60*1000）


mybatis:
  type-aliases-package: com.cssl.bean
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  auto-dialect: true
  page-size-zero: true
  reasonable: true