server:
  servlet:
    context-path: /redis
  port: 8083

#redis配置
spring:
  redis:
    database: 0
    password: 123456
    port: 6379
    timeout: 20s
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1
        min-idle: 0
    host: 192.168.88.146
